#define	CONSTANT 1
#define ID 2
#define SEMICOLON 3
#define KEYWORD 4
#define L_BRACKET 5
#define R_BRACKET 6
#define L_PARENT 7
#define R_PARENT 8
#define CHAR 9
#define STRING 10
#define QUOTE 11
#define APOS 12
